"""
Step 0b-B: MiniMax M3 Vision OCR (Recommended - uses Token Plan quota)

Input:  data/images/semester{n}_manifest.json  (generated by 00a)
Output: data/processed/raw_pages_semester{n}.json

Features:
  - Resume support: each page cached to data/ocr_cache/semester{n}/page_NNN.json
  - Auto-retry on failure (tenacity, 3 attempts)
  - Rate-limit friendly: 0.3s delay between pages
  - Skips semesters already processed as native PDF (no manifest)

Token estimate: ~130,000 tokens per semester (146 pages × ~900 tokens avg)
Monthly impact: < 0.05% of 0.5B token plan

.env required:
  MINIMAX_API_KEY=sk-cp-xxxx
  MINIMAX_MODEL=MiniMax-M3-highspeed   (or MiniMax-M3)
"""
import base64
import json
import os
import re
import time
from pathlib import Path

from dotenv import load_dotenv
from openai import OpenAI
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

load_dotenv()

MINIMAX_API_KEY  = os.getenv("MINIMAX_API_KEY")
MINIMAX_MODEL    = os.getenv("MINIMAX_MODEL", "MiniMax-M3")
MINIMAX_BASE_URL = "https://api.minimax.io/v1"

OCR_SYSTEM_PROMPT = """你是专业的英语教材 OCR 助手，专门处理人教版初中英语教材（Go for it! Grade 8）的扫描图片。

提取规则：
1. 提取图片中所有可见文字，包括正文、对话、词汇表、练习题、语法说明
2. 识别并标注结构：[UNIT N] [SECTION A/B] [GRAMMAR FOCUS] [VOCABULARY] [SELF CHECK]
3. 对话格式：A: ... / B: ...（保留说话人标识）
4. 词汇表：每词一行，格式 word /phonetic/ 中文释义
5. 填空题用 ___ 表示空格
6. 模糊处用 [不清晰] 标注
7. 直接输出提取的文字，不要添加解释或说明"""

OCR_USER_PROMPT = ("提取这张人教版八年级英语教材扫描页中的所有文字。"
                   "识别并标注单元和章节结构，保持对话、词汇表、练习题的原有格式。")


def init_client() -> OpenAI:
    if not MINIMAX_API_KEY:
        raise ValueError(
            "MINIMAX_API_KEY 未设置！\n"
            "请在 .env 中添加：MINIMAX_API_KEY=your-sk-cp-xxxx\n"
            "从 platform.minimax.io 获取"
        )
    client = OpenAI(api_key=MINIMAX_API_KEY, base_url=MINIMAX_BASE_URL)
    print(f"✅ MiniMax client ready (model: {MINIMAX_MODEL})")
    return client


def encode_image(image_path: str) -> str:
    with open(image_path, "rb") as f:
        return base64.standard_b64encode(f.read()).decode("utf-8")


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=2, min=3, max=20),
    retry=retry_if_exception_type(Exception),
)
def ocr_single_page(client: OpenAI, image_path: str) -> str:
    file_size_mb = Path(image_path).stat().st_size / (1024 * 1024)
    if file_size_mb > 9.5:
        print(f"    ⚠️  Image {file_size_mb:.1f}MB near 10MB limit")

    image_data = encode_image(image_path)
    response = client.chat.completions.create(
        model=MINIMAX_MODEL,
        max_tokens=2048,
        extra_body={"thinking": {"type": "disabled"}},
        messages=[
            {"role": "system", "content": OCR_SYSTEM_PROMPT},
            {
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:image/png;base64,{image_data}",
                            "detail": "high",
                        },
                    },
                    {"type": "text", "text": OCR_USER_PROMPT},
                ],
            },
        ],
    )
    return response.choices[0].message.content.strip()


def detect_unit(text: str, current_unit: str) -> str:
    cn_map = {"一": "1", "二": "2", "三": "3", "四": "4", "五": "5",
              "六": "6", "七": "7", "八": "8", "九": "9", "十": "10"}
    for pattern in [r"\[UNIT\s+(\d+)\]", r"Unit\s+(\d+)", r"UNIT\s+(\d+)"]:
        m = re.search(pattern, text, re.IGNORECASE)
        if m:
            return f"Unit {cn_map.get(m.group(1), m.group(1))}"
    return current_unit


def detect_section(text: str) -> str:
    for pattern, name in [
        (r"\[SECTION\s+A\]|Section\s+A", "Section A"),
        (r"\[SECTION\s+B\]|Section\s+B", "Section B"),
        (r"\[GRAMMAR\s+FOCUS\]|Grammar\s+Focus", "Grammar Focus"),
        (r"\[VOCABULARY\]|Vocabulary", "Vocabulary"),
        (r"\[SELF\s+CHECK\]|Self\s+Check", "Self Check"),
    ]:
        if re.search(pattern, text, re.IGNORECASE):
            return name
    return "General"


def process_semester(client: OpenAI, semester: int) -> list[dict]:
    manifest_path = f"data/images/semester{semester}_manifest.json"
    if not Path(manifest_path).exists():
        print(f"  ❌ No manifest — run 00a_pdf_to_images.py first")
        return []

    with open(manifest_path) as f:
        manifest = json.load(f)

    image_paths = manifest["image_paths"]
    total = len(image_paths)
    cache_dir = Path(f"data/ocr_cache/semester{semester}")
    cache_dir.mkdir(parents=True, exist_ok=True)

    pages: list[dict] = []
    current_unit = "Unit 1"
    cached = processed = errors = 0
    start = time.time()

    print(f"\n=== MiniMax M3 OCR: Semester {semester} ({total} pages) ===")
    print(f"    Cache dir: {cache_dir}")

    for idx, image_path in enumerate(image_paths):
        page_num = idx + 1
        cache_file = cache_dir / f"page_{page_num:03d}.json"

        # Resume: load from cache if available
        if cache_file.exists():
            with open(cache_file, encoding="utf-8") as f:
                data = json.load(f)
            pages.append(data)
            current_unit = data.get("unit", current_unit)
            cached += 1
            continue

        eta = ""
        if processed > 0:
            avg_sec = (time.time() - start) / processed
            remaining = avg_sec * (total - idx)
            eta = f"ETA ~{remaining / 60:.1f}min"

        print(f"  [{page_num:3d}/{total}] OCR... {eta}")

        try:
            text = ocr_single_page(client, image_path)

            if len(re.sub(r"\s+", "", text)) < 25:
                processed += 1
                time.sleep(0.3)
                continue

            current_unit = detect_unit(text, current_unit)
            section = detect_section(text)

            page_data = {
                "page_num": page_num,
                "text": text,
                "unit": current_unit,
                "section": section,
                "semester": semester,
                "ocr_method": "minimax_m3",
                "char_count": len(text),
            }

            with open(cache_file, "w", encoding="utf-8") as f:
                json.dump(page_data, f, ensure_ascii=False, indent=2)

            pages.append(page_data)
            print(f"    → {current_unit} | {section} | {len(text)} chars")
            processed += 1
            time.sleep(0.3)

        except Exception as e:
            print(f"    ❌ Page {page_num} error: {e}")
            errors += 1
            processed += 1
            time.sleep(2)

    elapsed = (time.time() - start) / 60
    print(f"\n✅ Semester {semester}: {elapsed:.1f}min | "
          f"processed={processed} cached={cached} errors={errors}")
    return pages


def save_results(pages: list[dict], semester: int):
    Path("data/processed").mkdir(parents=True, exist_ok=True)
    output_path = f"data/processed/raw_pages_semester{semester}.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(pages, f, ensure_ascii=False, indent=2)

    unit_counts: dict[str, int] = {}
    for p in pages:
        u = p.get("unit", "Unknown")
        unit_counts[u] = unit_counts.get(u, 0) + 1

    print(f"💾 {len(pages)} pages → {output_path}")
    for u in sorted(unit_counts):
        print(f"  {u}: {unit_counts[u]} pages")


def main():
    print("=" * 55)
    print("Step 0b-B: MiniMax M3 Vision OCR")
    print("=" * 55)
    print(f"Model : {MINIMAX_MODEL}")
    print(f"Tokens: ~130,000 per semester (<0.05% of monthly plan)")
    print()

    client = init_client()

    for semester in [1, 2]:
        manifest   = f"data/images/semester{semester}_manifest.json"
        processed  = f"data/processed/raw_pages_semester{semester}.json"

        # Skip if native PDF already extracted by 00a
        if Path(processed).exists() and not Path(manifest).exists():
            print(f"\nSemester {semester}: already extracted (native PDF), skipping.")
            continue

        if not Path(manifest).exists():
            print(f"\nSemester {semester}: no manifest found, skipping.")
            continue

        pages = process_semester(client, semester)
        if pages:
            save_results(pages, semester)

    print("\n🎉 MiniMax OCR complete!")
    print("Next: python scripts/00c_verify_ocr.py")


if __name__ == "__main__":
    main()
